development:
  adapter: postgresql
  encoding: utf8
  database: breaking_development
  pool: 5
  username: 
  password:

test: 
  adapter: postgresql
  encoding: utf8
  database: breaking_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: breaking_production
  pool: 5
  username: 
  password:
